### ISSUE TITLE
Reminder: New CartoDB Accounts Should Use cartodb.js versions >= 3.15

### ISSUE THREAD

**Issue by ranchodeluxe** [stamen/cityenergy#10]
A note for future energy benchmarking projects.

Carto changed their name and the domain to access the SQL api -- `<cartouser>.carto.com/v2/api/sql`. Changing the domain alone does not render the tiles even though the requests returned payloads. Upgrading to `cartodb.js` version `3.15` from `3.14` was the fix

**Comment by sconnelley** [comment]
This seems done...
