### ISSUE TITLE
Menus width and show all/ hide all selections 

### ISSUE THREAD

**Issue by emilyhobson** [stamen/cityenergy#15]
Menus vary in width depending on the description of the Heading which leads to left/right . This is causing the show all | hide all to break in a weird place and to introduce an awkward horizontal scroll. 

![image](https://cloud.githubusercontent.com/assets/824082/17990580/018f2588-6aec-11e6-9604-f39105059998.png)

![image](https://cloud.githubusercontent.com/assets/824082/17990732/3957f69c-6aed-11e6-877a-058eaefa3896.png)

**Comment by sconnelley** [comment]
![image](https://cloud.githubusercontent.com/assets/565486/18399650/fdaf8574-769f-11e6-929f-c2d69f209892.png)
