### ISSUE TITLE
toLocaleString() doesn't work in Safari

### ISSUE THREAD

**Issue by sethfitz** [stamen/cityenergy#8]
As a result, numbers don't include commas.

This may also occur in other browsers.

**Comment by sconnelley** [comment]
Adding this to INTL polyfill fixes `<script src="https://cdn.polyfill.io/v2/polyfill.js?features=Intl.~locale.en-US|always&gated=0"></script>`

**Comment by sconnelley** [comment]
https://github.com/cityenergyproject/dc/commit/fcfa9719b9196fa4d936065f8e6850f649ea7b04#diff-e249faefed5757034596c5096d33dab6R9
